config/routes.rb
Rails.application.routes.draw do

  root to: 'timelines#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    cofirmations: 'users/confirmations',
  }
  
  resources :profiles, except: %i(index show destroy)
  resources :timelines, only: %i(index create)
  resources :users, only: [:index] do
    resources :profiles, only: [:show]
    resources :replies, only: [:index]
  end
  resources :tweets, only: %i(show destroy) do
    resources :replies, except: %i(index show new)
  end

  post 'follow/:id', to: 'relationships#follow', as: 'follow'
  post 'unfollow/:id', to: 'relationships#unfollow', as: 'unfollow'
  get 'followindex/:id', to: 'users#followindex', as: 'followindex'
  get 'followerindex/:id', to: 'users#followerindex', as: 'followerindex'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :self_introduction, :live_in, :birthday, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: %i(edit update)

  def show
    @profile = Profile.find(params[:id])
    @user = User.find(params[:user_id])
    @tweets = Tweet.where(user_id: params[:user_id]).order(created_at: :desc).page(params[:page])
    session[:path_back_from_tweet] = user_profile_path(current_user)
  end

  def new
    @profile = current_user.build_profile
    render layout: "login"
  end

  def edit
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to users_path, notice: '新規登録完了。まずは誰かをフォローしてみよう！'
    else
      render :new, layout: "login"
    end
  end

  def update
    if current_user.profile.update(profile_params)
      redirect_to user_profile_path(current_user, @profile), notice: '更新完了'
    else
      render :edit
    end
  end

  private

    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:self_introduction, :birthday, :live_in, :image)
    end

end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="form-group">
    <div class="col rounded bg-info">
      <div class="field">
        <label>
          <div>
            <%= f.label :プロフィール画像 %>
          </div>
          <div id="img_field" class="btn btn-link">
            <% if profile.image.present? %>
              <%= image_tag profile.image.variant(resize_to_fill:[80,80]).processed, class:"rounded-circle" %>
            <% else %>
              <div>
              <i class="fas fa-file-image"></i>
              画像を選択
              </div>
            <% end %>
          </div>
          <div class="row btn btn-link">
            <%= f.file_field :image, class:"image", style:"display:none", id: "file" %>
          </div>
        </label>
      </div>
    </div>
    <br>
    <div class="col rounded bg-info">
      <div class="field">
        <%= f.label :自己紹介 %>
        <%= f.text_area :self_introduction, class: "form-control-plaintext text-white" %>
      </div>
    </div>
    <br>
    <div class="col rounded bg-info">
      <div class="field">
        <%= f.label :居住地 %>
        <%= f.text_field :live_in, class: "form-control-plaintext text-white" %>
      </div>
    </div>
    <br>
    <div class="col rounded bg-info">
      <div class="field">
        <%= f.label :"誕生日" %>
        <%= f.text_field :birthday, placeholder: "0000-00-00", class: "form-control-plaintext text-white" %>
      </div>
    </div>
    <br>
    <div class="actions">
      <%= f.submit("登録", class: "btn btn-primary") %>
    </div>
  </div>
<% end %>

app/views/profiles/_image.html.erb
<div class="col-4 col-sm-3">
  <% if profile.image.present? %>
    <%= image_tag profile.image.variant(resize_to_fill:[80,80]).processed, class:"rounded-circle" %>
  <% else %>
    <i class="fas fa-user-circle fa-5x" style="color: silver"></i>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="row align-items-center py-1">
  <div class="col-2 col-sm-1">
	  <div class="h3 font-weight-bold">
      <%= link_to "←", user_profile_path(current_user, current_user.profile) %>
    </div>
  </div>
  <div class="col-10 col-sm-11 h3">
    プロフィール編集
  </div>
</div>
<%= render 'form', profile: @profile %>

app/views/profiles/new.html.erb
<div class="row h3 py-1">
  プロフィール登録
</div>
<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<div class="row align-items-center py-1">
  <div class="col-2 col-sm-1">
    <div class="h3 font-weight-bold">
      <%= link_to "←", session[:path_back_from_profile] %>
    </div>
  </div>
  <div class="col-10 col-sm-11 h3">
    <%= @user.name %>
  </div>
</div>
<div class="row align-items-end">
  <div class="col-5">
    <%= render 'image', profile: @profile %>
  </div>
  <div class="col-7">
    <% if @user.id == current_user.id %>
      <div class="row">
        <div>
          <%= link_to 'プロフィール編集', edit_profile_path(current_user), class:"btn btn-sm btn-outline-primary" %>
        </div>
      </div>
      <div class="row pt-1">
        <div>
          <%= link_to '過去のコメント', user_replies_path(current_user), class:"btn btn-sm btn-outline-primary" %>
        </div>
      </div>
    <% else %>
      <div class="row">
      <% if current_user.following?(@user) %>
        <div>
          <%= link_to 'フォローを外す', unfollow_path(@user), method: :POST, class: "btn btn-sm btn-outline-primary" %>
        </div>
      <% else %>
        <div>
          <%= link_to 'フォローする', follow_path(@user), method: :POST, class: "btn btn-sm btn-primary text-info" %>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <%= simple_format(@profile.self_introduction) %>
  </div>
</div>
<div class="row py-1">
  <div class="col">
    フォロー数 :　　
    <%= @user.follower.count %>
    　　
    <%= link_to "内訳", followindex_path(@user.id) %>
  </div>
</div>
<div class="row py-1">
  <div class="col">
    フォロワー数 :　
    <%= @user.followed.count %>
    　　
    <%= link_to "内訳", followerindex_path(@user.id) %>
  </div>
</div>
<div class="row py-1">
  <div class="col-5">
    誕生日:
  </div>
  <div class="col-7">
    <% if @profile.birthday.present? %>
      <%= l @profile.birthday, format: :default%>
    <% end %>
  </div>
</div>
<div class="row py-1">
  <div class="col-5">
    居住地:
  </div>
  <div class="col-7">
    <%= @profile.live_in %>
  </div>
</div>
<div class="row pt-1 pb-2">
  <div class="col-5">
    登録日:
  </div>
  <div class="col-7">
    <%= l @profile.created_at, format: :date_only %>
  </div>
</div>
<div class="row border-top border-secondary py-1">
  <div class="col">
    過去の投稿
  </div>
</div>
<%= render @tweets %>
<div class="row border-top border-secondary  justify-content-center">
  <%= paginate @tweets %>
</div>