config/routes.rb
Rails.application.routes.draw do

  root to: 'timelines#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    cofirmations: 'users/confirmations',
  }
  
  resources :profiles, except: %i(index show destroy)
  resources :timelines, only: %i(index create)
  resources :users, only: [:index] do
    resources :profiles, only: [:show]
    resources :replies, only: [:index]
  end
  resources :tweets, only: %i(show destroy) do
    resources :replies, except: %i(index show new)
  end

  post 'follow/:id', to: 'relationships#follow', as: 'follow'
  post 'unfollow/:id', to: 'relationships#unfollow', as: 'unfollow'
  get 'followindex/:id', to: 'users#followindex', as: 'followindex'
  get 'followerindex/:id', to: 'users#followerindex', as: 'followerindex'

end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates :comment, presence: true, length: {maximum: 140 }
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_tweet, only: %i(edit create update destroy)
  before_action :set_reply, only: %i(edit update destroy)

  def index
    @replies = current_user.replies.order(created_at: :desc).page(params[:page])
  end

  def edit
  end

  def create
    @reply = @tweet.replies.build(user: current_user, comment: reply_params[:comment])
    respond_to do |format|
      if @reply.save
        format.js
      else
        format.js {render 'new'}
      end
    end
  end

  def update
    if @reply.update(reply_params)
      redirect_to user_replies_path(current_user), notice: '更新完了'
    else
      render :edit
    end
  end

  def destroy
    @reply.destroy
    redirect_to user_replies_path(current_user), notice: '削除完了'
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    def set_reply
      @reply = current_user.replies.find(params[:id])
    end

    def reply_params
      params.require(:reply).permit(:comment)
    end
end

app/views/replies/_error_explanation_message.html.erb
<% @reply.errors.full_messages.each do |message| %>
  <li>
    <%= message %>
  </li>
<% end %>

app/views/replies/_form.html.erb
<%= form_with(model: [@tweet, reply]) do |f| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% reply.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row border-top border-secondary align-items-center py-2">
    <div class="col-1 col-sm-1">
      <i class="fas fa-reply"></i>
    </div>
    <%= render 'profiles/image', profile: current_user.profile %>
    <div class="col-4 col-sm-6">
      <%= f.text_area :comment, placeholder: "コメントを入力", class: "form-control-plaintext text-white"%>
			<div id="error_explanation"></div>
    </div>
    <div class="col-2 col-sm-2">
      <%= f.submit("投稿", class: "btn btn-sm btn-primary") %>
    </div>
  </div>

<% end %>

app/views/replies/_reply.html.erb
<div class="row border-top border-secondary align-items-center py-2">
  <div class="col-1">
    <i class="fas fa-reply"></i>
  </div>
  <%= render 'profiles/image', profile: Profile.find_by(user: reply.user) %>
  <div class="col-6 col-sm-8">
    <div class="row">
      <%= User.find(reply.user_id).name %>
    </div>
    <div>
      <%= safe_join(reply.comment.split("\n"), tag(:br)) %>
    </div>
    <div class="text-secondary">
      <%= l reply.created_at, format: :short %>
    </div>
  </div>
</div>

app/views/replies/create.js.erb
document.getElementById('replies').insertAdjacentHTML('AfterBegin', '<%= j(render 'replies/reply', reply: @reply) %>')

document.getElementById('reply_comment').value = ''

$('#error_explanation').html("");

app/views/replies/edit.html.erb
<div class="row align-items-center py-1">
  <div class="col-2 col-sm-1">
	  <div class="h3 font-weight-bold">
      <%= link_to "←", user_replies_path(current_user) %>
    </div>
  </div>
  <div class="col-10 col-sm-11 h3">
    コメントを編集
  </div>
</div>
</div>
<div class="row border-top border-secondary align-items-center py-2">
  <%= render 'profiles/image', profile: Profile.find_by(user: @tweet.user) %>
  <div class="col-8 col-sm-9">
    <div class="row">
      <%= @tweet.user.name %>
    </div>
    <div>
    <%= safe_join(@tweet.content.split("\n"), tag(:br)) %>
		</div>
    <div class="text-secondary">
      <%= l @tweet.created_at, format: :short %>
    </div>
	</div>
</div>
<%= render 'form', reply: @reply %>

app/views/replies/index.html.erb
<div class="row align-items-center py-1">
  <div class="col-2 col-sm-1">
    <div class="h3 font-weight-bold">
      <%= link_to "←", user_profile_path(current_user, current_user.profile) %>
    </div>
  </div>
  <div class="col-10 col-sm-11 h3">
    過去のコメント
  </div>
</div>

<% @replies.each do |reply| %>
  <% tweet = Tweet.find(reply.tweet_id) %>
  <div class="row border-top border-secondary align-items-center py-2">
  <%= render 'profiles/image', profile: Profile.find_by(user_id: tweet.user_id) %>
    <div class="col-8 col-sm-9">
      <div class="row">
        <%= tweet.user.name %>
      </div>
      <div>
        <%= tweet.content %>
      </div>
    </div>
  </div>
  <div class="row border-top border-secondary align-items-center py-2">
    <div class="col-1">
      <i class="fas fa-reply"></i>
    </div>
    <%= render 'profiles/image', profile: current_user.profile %>
    <div class="col-4 col-sm-6">
      <div class="row">
        <%= current_user.name %>
      </div>
      <div>
        <%= reply.comment %>
      </div>
    </div>
    <div class="col-2 col-sm-2">
      <div class="row">
        <div class="col px-0 text-center">
          <%= link_to "編集", edit_tweet_reply_path(tweet, reply) %>
        </div>
      </div>
      <div class="row">
        <div class="col px-0 text-center">
          <%= link_to '削除', tweet_reply_path(tweet, reply), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="row border-top border-secondary align-content-center">
  <%= paginate @replies %>
</div>

app/views/replies/new.js.erb
$('#error_explanation').html("<%= j(render 'error_explanation_message') %>");