config/routes.rb
Rails.application.routes.draw do

  root to: 'timelines#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    cofirmations: 'users/confirmations',
  }
  
  resources :profiles, except: %i(index show destroy)
  resources :timelines, only: %i(index create)
  resources :users, only: [:index] do
    resources :profiles, only: [:show]
    resources :replies, only: [:index]
  end
  resources :tweets, only: %i(show destroy) do
    resources :replies, except: %i(index show new)
  end

  post 'follow/:id', to: 'relationships#follow', as: 'follow'
  post 'unfollow/:id', to: 'relationships#unfollow', as: 'unfollow'
  get 'followindex/:id', to: 'users#followindex', as: 'followindex'
  get 'followerindex/:id', to: 'users#followerindex', as: 'followerindex'

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController

  def index
    if current_user.profile.present?
      @timelines = Tweet.where(user: current_user).or(Tweet.where(user: current_user.following_user)).order(created_at: :desc).page(params[:page]).per(20)
      @tweet = current_user.tweets.build
      session[:path_back_from_profile] = root_path
      session[:path_back_from_tweet] = root_path
    else
      redirect_to new_profile_path(current_user)
    end
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.js
      else
        format.js {render 'new'}
      end
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:user_id, :content)
    end

end

app/views/timelines/_error_explanation_message.html.erb
<% @tweet.errors.full_messages.each do |message| %>
  <li>
    <%= message %>
  </li>
<% end %>

app/views/timelines/_form.html.erb
<%= form_with(model: tweet, url: timelines_path) do |f| %>
	<div class="row align-items-center py-2">
		<div class="col-4 col-sm-3">
			<% if current_user.profile.image.present? %>
				<%= image_tag current_user.profile.image.variant(resize_to_fill:[80,80]).processed, class:"rounded-circle" %>
				<%= link_to "", user_profile_path(current_user, current_user.profile), class:"stretched-link" %>
			<% else %>
				<i class="fas fa-user-circle fa-5x" style="color: silver"></i>
			<% end %>
		</div>
		<div class="col-5 col-sm-7">
			<%= f.text_area :content, placeholder: "耳寄り情報をつぶやいてみよう", class: "form-control-plaintext text-white"%>
			<div id="error_explanation"></div>
		</div>
		<div class="col-3 col-sm-2">
			<%= f.submit("投稿", class: "btn btn-sm btn-primary") %>
		</div>
	</div>
<% end %>

app/views/timelines/_timeline.html.erb
<div class="row border-top border-secondary align-items-center py-2">
  <div class="col-4 col-sm-3">
    <% if tweet.user.profile.image.present? %>
      <%= image_tag tweet.user.profile.image.variant(resize_to_fill:[80,80]).processed, class:"rounded-circle" %>
      <%= link_to "", user_profile_path(tweet.user.id, tweet.user.profile.id), class:"stretched-link" %>
    <% else %>
      <i class="fas fa-user-circle fa-5x" style="color: silver"></i>
      <%= link_to "", user_profile_path(tweet.user.id, tweet.user.profile.id), class:"stretched-link" %>
    <% end %>
  </div>
  <div class="col-6 col-sm-7">
    <div class="row">
      <%= tweet.user.name %>
    </div>
    <div>
      <%= safe_join(tweet.content.split("\n"), tag(:br)) %>
    </div>
    <div>
      <%= link_to "", tweet_path(tweet), class:"stretched-link" %>
    </div>
    <div class="text-secondary">
      <%= l tweet.created_at, format: :short %>
    </div>
  </div>
  <div class="col-2 col-sm-2 h4 align-self-end text-center">
    <%= link_to "💬", tweet_path(tweet)%>
  </div>
</div>

app/views/timelines/create.js.erb
document.getElementById('timelines').insertAdjacentHTML('AfterBegin', '<%= j(render 'timeline', tweet: @tweet) %>')

document.getElementById('tweet_content').value = ''

$('#error_explanation').html("");

app/views/timelines/index.html.erb
<div class="row py-1">
  <div class="col h3">
    Home
  </div>
</div>
<%= render partial: 'timelines/form', locals: {tweet: @tweet} %>
<div id="timelines">
  <%= render partial: 'timeline', collection: @timelines, as: 'tweet' %>
</div>
<div class="row border-top border-secondary justify-content-center">
  <%= paginate @timelines %>
</div>

app/views/timelines/new.js.erb
$('#error_explanation').html("<%= j(render 'error_explanation_message') %>");