config/routes.rb
Rails.application.routes.draw do

  root to: 'timelines#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    cofirmations: 'users/confirmations',
  }
  
  resources :profiles, except: %i(index show destroy)
  resources :timelines, only: %i(index create)
  resources :users, only: [:index] do
    resources :profiles, only: [:show]
    resources :replies, only: [:index]
  end
  resources :tweets, only: %i(show destroy) do
    resources :replies, except: %i(index show new)
  end

  post 'follow/:id', to: 'relationships#follow', as: 'follow'
  post 'unfollow/:id', to: 'relationships#unfollow', as: 'unfollow'
  get 'followindex/:id', to: 'users#followindex', as: 'followindex'
  get 'followerindex/:id', to: 'users#followerindex', as: 'followerindex'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>komimi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <div class="container text-light">
      <div class="row">
        <div class="col-2 text-center h3 sticky-top" style="height: 100%">
          <div>
            <%= link_to root_path, style: "color: white", class:"btn btn-dark btn-lg px-0" do %>
              <i class="fab fa-twitter"></i>
            <% end %>
          </div>
          <div>
            <%= link_to root_path, style: "color: white", class:"btn btn-dark btn-lg px-0" do %>
              <i class="fas fa-home"></i>
            <% end %>
          </div>
          <div>
            <%= link_to user_profile_path(current_user, current_user.profile), style:"color: white", class:"btn btn-dark btn-lg px-0" do %>
              <i class="fas fa-user"></i>
            <% end %>
          </div>
          <div>
            <%= link_to users_path, style:"color: white", class:"btn btn-dark btn-lg px-0" do %>
              <i class="fas fa-users"></i>
            <% end %>
          </div>
          <div>
            <%= link_to destroy_user_session_path, method: :delete, style:"color: white", class:"btn btn-dark btn-lg px-0" do %>
              <i class="fas fa-sign-out-alt"></i>
            <% end %>
          </div>
        </div>
        <div class="col-9 border border-secondary">
          <% if notice %>
            <div id="notice" class="notice col rounded bg-info py-2">
          　　<%= notice %>
            </div>
          <% end %>
          <% if alert %>
            <div id="alert" class="alert col rounded bg-info py-2">
              <%= alert %>
            </div>
          <% end %>
          <div>
            <%= yield %>
          </div>
          </div>
        <div class="col-1">
          <div class="row">
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Komimi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <div class="container text-light">
      <div class="row justify-content-center">
        <div class="col-10 col-md-6">
          <% if notice %>
            <div id="notice" class="notice col rounded bg-info py-2">
          　　<%= notice %>
            </div>
          <% end %>
          <% if alert %>
            <div id="alert" class="alert col rounded bg-info py-2">
              <%= alert %>
            </div>
          <% end %>
          <div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>